### Ortak Değişkenler
@baseUrl = http://127.0.0.1:8000/api
@contentType = application/json

### Birimler - Oluştur
# @name createBirim
POST {{baseUrl}}/birimler
Content-Type: {{contentType}}

{
  "birim_adi": "Dış İlişkiler",
  "konumu": "B Blok"
}

### Birimler - Listele
GET {{baseUrl}}/birimler

### Birimler - Arama (q ile birim_adi LIKE)
GET {{baseUrl}}/birimler?q=mali

### Birimler - Detay (createBirim yanıtından id kullanır)
GET {{baseUrl}}/birimler/2

### Birimler - Güncelle (PATCH)
PATCH {{baseUrl}}/birimler/2
Content-Type: {{contentType}}

{
  "konumu": "B Blok"
}

### Birimler - Sil
DELETE {{baseUrl}}/birimler/2

### Unvanlar - Oluştur
# @name createUnvan
POST {{baseUrl}}/unvanlar
Content-Type: {{contentType}}

{
  "unvan_adi": "Birim Yöneticisi"
}

### Unvanlar - Listele
GET {{baseUrl}}/unvanlar

### Unvanlar - Detay (createUnvan yanıtından id kullanır)
GET {{baseUrl}}/unvanlar/2

### Unvanlar - Güncelle (PUT)
PUT {{baseUrl}}/unvanlar/2
Content-Type: {{contentType}}

{
  "unvan_adi": "Kıdemli Uzman"
}

### Unvanlar - Sil
DELETE {{baseUrl}}/unvanlar/2



### personel - Oluştur
# @name createPersonel
POST {{baseUrl}}/personel
Content-Type: {{contentType}}

{
  "adi_soyadi": "Nuri Akman",
  "unvan_id": 1,
  "birim_id": 2,
  "notlar": "Eskilerden"
}

### personel - Listele
GET {{baseUrl}}/personel

### personel - Detay (createPersonel yanıtından id kullanır)
GET {{baseUrl}}/personel/{{createPersonel.response.body.$.id}}

### personel - Güncelle (PATCH)
PATCH {{baseUrl}}/personel/{{createPersonel.response.body.$.id}}
Content-Type: {{contentType}}

{
  "notlar": "Güncellendi"
}

### personel - Sil
DELETE {{baseUrl}}/personel/{{createPersonel.response.body.$.id}}

